# Largely built from this excellent guide:
# https://shift.click/blog/github-actions-rust/#run-on-pushes-to-main--prs-to-main-or-dev

name: Test

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { rust: stable, os: ubuntu-latest }
        - { rust: nightly, os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - run: cargo test
      - run: cargo clippy
      - run: cargo fmt -- --check
